backend:
  name: git-gateway

media_folder: content/assets
public_folder: ../assets

collections:
  - name: aboutpage
    label: Subpages / About Page
    folder: content/about-page
    create: true
    fields:
      - { name: shorttitle, label: Short Title }
      - { name: title, label: SEO Title }
      - { name: description, label: SEO Description }
      - name: hero
        label: Hero
        widget: object
        fields:
          - { name: headingone, label: H1, widget: text }
          - { name: subheading, label: Subheading, widget: text }
      - { name: body, label: Body, widget: markdown }

  - name: cookiespage
    label: Subpages / Cookie Page
    folder: content/cookie-page
    create: true
    fields:
      - { name: shorttitle, label: Short Title }
      - { name: title, label: SEO Title }
      - { name: description, label: SEO Description }
      - name: hero
        label: Hero
        widget: object
        fields:
          - { name: headingone, label: H1, widget: text }
          - { name: subheading, label: Subheading, widget: text }
      - { name: body, label: Body, widget: markdown }

  - name: contactpage
    label: Subpages / Contact Page
    folder: content/contact-page
    create: true
    fields:
      - { name: shorttitle, label: Short Title }
      - { name: title, label: SEO Title }
      - { name: description, label: SEO Description }
      - name: hero
        label: Hero
        widget: object
        fields:
          - { name: headingone, label: H1, widget: text }
          - { name: subheading, label: Subheading, widget: text }
      - name: contactoptions
        label: Contact Options
        widget: object
        fields:
          - name: call
            label: Call
            widget: object
            fields:
              - { name: heading, label: Heading, widget: text }
              - { name: contactinfo, label: Contact Information, widget: text }
              - { name: contactlink, label: Contact Link, widget: text }
          - name: email
            label: Email
            widget: object
            fields:
              - { name: heading, label: Heading, widget: text }
              - { name: contactinfo, label: Contact Information, widget: text }
              - { name: contactlink, label: Contact Link, widget: text }

  - name: sponsorspage
    label: Subpages / Sponsors Page
    folder: content/sponsors-page
    create: true
    fields:
      - { name: shorttitle, label: Short Title }
      - { name: title, label: SEO Title }
      - { name: description, label: SEO Description }
      - name: hero
        label: Hero
        widget: object
        fields:
          - { name: headingone, label: H1, widget: text }
          - { name: subheading, label: Subheading, widget: text }
      - name: sponsorcontent
        label: Sponsor Content
        widget: object
        fields:
          - {
              name: mainsponsorstitle,
              label: Main Sponsors Title,
              widget: text,
            }
          - {
              name: eventsponsorstitle,
              label: Event Sponsors Title,
              widget: text,
            }
      - name: becomesponsor
        label: Become a Sponsor Section
        widget: object
        fields:
          - { name: headingtwo, label: H2, widget: text }
          - { name: description, label: Description, widget: text }
          - { name: link, label: E-mail Address, widget: text }

  - name: events
    label: Subpages / Events Pages
    folder: content/events
    create: true
    fields:
      - { name: shorttitle, label: Short Title }
      - { name: title, label: SEO Title }
      - { name: description, label: SEO Description }
      - name: hero
        label: Hero
        widget: object
        fields:
          - { name: headingone, label: H1, widget: text }
          - { name: subheading, label: Subheading, widget: text }

  - name: footer
    label: Sections / Footer
    folder: content/footer
    create: true
    fields:
      - { name: name, label: Identifier }
      - { name: title, label: Footer Title }
      - { name: copyright, label: Copyright/Cookie Policy, widget: markdown }
      - { name: linkscenter, label: Links Column, widget: markdown }
      - { name: linksright, label: Links Column, widget: markdown }

  - name: hostevent
    label: Sections / Host Event
    folder: content/host-event
    create: true
    fields:
      - { name: name, label: Identifier }
      - { name: title, label: Form Title }
      - name: when
        label: When Input
        widget: object
        fields:
          - { name: label, label: Label, widget: string }
          - { name: placeholder, label: Placeholder, widget: string }
      - name: howmany
        label: How Many Input
        widget: object
        fields:
          - { name: label, label: Label, widget: string }
          - { name: placeholder, label: Placeholder, widget: string }
      - name: where
        label: Where Input
        widget: object
        fields:
          - { name: label, label: Label, widget: string }
          - { name: placeholder, label: Placeholder, widget: string }
      - name: email
        label: Email Input
        widget: object
        fields:
          - { name: label, label: Label, widget: string }
          - { name: placeholder, label: Placeholder, widget: string }
      - name: thankyou
        label: Thank You Page
        widget: object
        fields:
          - { name: shorttitle, label: Short Title }
          - { name: title, label: SEO Title }
          - { name: description, label: SEO Description }
          - name: hero
            label: Hero
            widget: object
            fields:
              - { name: headingone, label: H1, widget: text }
              - { name: subheading, label: Subheading, widget: text }

  - name: sponsors
    label: Sponsors
    folder: content/sponsors
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: logo, label: Logo, widget: image, allow_multiple: false }
      - { name: url, label: URL }
      - { name: color, label: Card Color }
      - { name: body, label: Body, widget: markdown }
      - {
          label: Sponsor Type,
          name: sponsortype,
          widget: select,
          options: [main, event],
        }

  - name: coming-events
    label: Events / Coming Events
    folder: content/coming-events
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: ingress, label: Ingress, widget: text }
      - {
          name: featuredimage,
          label: Featured Image,
          widget: image,
          allow_multiple: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: past-events
    label: Events / Past Events
    folder: content/past-events
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: ingress, label: Ingress, widget: text }
      - {
          name: featuredimage,
          label: Featured Image,
          widget: image,
          allow_multiple: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: start-page
    label: Index / Start Page
    folder: content/start-page
    create: true
    identifier_field: name
    fields:
      - { name: name, label: Identifier }
      - { name: title, label: SEO Title }
      - { name: description, label: SEO Description }
      - name: hero
        label: Hero
        widget: object
        fields:
          - { name: headingone, label: H1, widget: text }
          - { name: subtitlelinktext, label: Link Text, widget: text }
          - {
              name: subtitlelinkdestination,
              label: Subtitle Link Destination,
              widget: string,
            }
      - name: events
        label: Events
        widget: object
        fields:
          - {
              name: nexteventtitle,
              label: Title for featured upcoming events,
              widget: string,
            }
          - {
              name: nexteventbuttontext,
              label: Next events button text,
              widget: string,
            }
          - {
              name: nexteventbuttondestination,
              label: Next events button destination,
              widget: string,
            }
          - {
              name: pasteventtitle,
              label: Title for featured past events,
              widget: string,
            }
          - {
              name: pasteventbuttontext,
              label: Past events button text,
              widget: string,
            }
          - {
              name: pasteventbuttondestination,
              label: Past events button destination,
              widget: string,
            }
      - name: about
        label: About
        widget: object
        fields:
          - { name: headingtwo, label: H2, widget: text }
          - { name: s, label: Content for S-section, widget: markdown }
          - { name: e, label: Content for E-section, widget: markdown }
          - { name: o, label: Content for O-section, widget: markdown }
