backend:
  name: github
  repo: kumpan/seogirls

media_folder: static/assets
public_folder: assets

collections:
  - name: events
    label: Events Pages
    folder: content/events
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: SEO Title }
      - { name: description, label: SEO Description }
      - name: hero
        label: Hero
        widget: object
        fields:
          - { name: headingone, label: H1, widget: text }
          - { name: subheading, label: Subheading, widget: text }

  - name: footer
    label: Footer
    folder: content/footer
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Footer Title }
      - { name: copyright, label: Copyright/Cookie Policy, widget: markdown }
      - { name: linkscenter, label: Links Column, widget: markdown }
      - { name: linksright, label: Links Column, widget: markdown }

  - name: sponsors
    label: Sponsors
    folder: content/sponsors
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: logo, label: Logo, widget: image, allow_multiple: false }
      - { name: url, label: URL }
      - { name: body, label: Body, widget: markdown }

  - name: coming-events
    label: Coming Events
    folder: content/coming-events
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: ingress, label: Ingress, widget: text }
      - {
          name: featuredimage,
          label: Featured Image,
          widget: image,
          allow_multiple: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: past-events
    label: Past Events
    folder: content/past-events
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: ingress, label: Ingress, widget: text }
      - {
          name: featuredimage,
          label: Featured Image,
          widget: image,
          allow_multiple: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: start-page
    label: Start Page
    folder: content/start-page
    create: true
    identifier_field: name
    fields:
      - { name: name, label: Identifier }
      - { name: title, label: SEO Title }
      - { name: description, label: SEO Description }
      - name: hero
        label: Hero
        widget: object
        fields:
          - { name: headingone, label: H1, widget: text }
          - { name: subtitlelinktext, label: Link Text, widget: text }
          - {
              name: subtitlelinkdestination,
              label: Subtitle Link Destination,
              widget: string,
            }
      - name: events
        label: Events
        widget: object
        fields:
          - {
              name: nexteventtitle,
              label: Title for featured upcoming events,
              widget: string,
            }
          - {
              name: nexteventbuttontext,
              label: Next events button text,
              widget: string,
            }
          - {
              name: nexteventbuttondestination,
              label: Next events button destination,
              widget: string,
            }
          - {
              name: pasteventtitle,
              label: Title for featured past events,
              widget: string,
            }
          - {
              name: pasteventbuttontext,
              label: Past events button text,
              widget: string,
            }
          - {
              name: pasteventbuttondestination,
              label: Past events button destination,
              widget: string,
            }
      - name: about
        label: About
        widget: object
        fields:
          - { name: headingtwo, label: H2, widget: text }
          - { name: s, label: Content for S-section, widget: markdown }
          - { name: e, label: Content for E-section, widget: markdown }
          - { name: o, label: Content for O-section, widget: markdown }
